---
- name: ensure credentials.ini exists
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: answer
    value: 42
  when: local_dir is defined

- name: load mysql_root_password from credentials.ini
  set_fact:
    mysql_root_password: "{{ lookup( 'ini', 'mysql_root_password file={{ local_dir }}/credentials.ini default=password' ) }}"
  when: local_dir is defined and ( mysql_root_password == '' or mysql_root_password == [] )

- name: load mysql_user from credentials.ini
  set_fact:
    mysql_user: "{{ lookup( 'ini', 'mysql_user file={{ local_dir }}/credentials.ini default=dev' ) }}"
  when: local_dir is defined and ( mysql_user == '' or mysql_user == [] )

- name: load mysql_password from credentials.ini
  set_fact:
    mysql_password: "{{ lookup( 'ini', 'mysql_password file={{ local_dir }}/credentials.ini default=password' ) }}"
  when: local_dir is defined and ( mysql_password == '' or mysql_password == [] )

- name: write generated items to credentials.ini
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: "mysql_root_password", value: "{{ mysql_root_password }}" }
    - { option: "mysql_user",          value: "{{ mysql_user }}"          }
    - { option: "mysql_password",      value: "{{ mysql_password }}"      }
  when: local_dir is defined
