---
- stat:
    path: "{{ local_dir }}/ansible.id_rsa.pub"
  register: authorized_keys
  when: local_dir is defined

- name: copy in ansible user authorized_keys
  copy:
    src: "{{ local_dir }}/ansible.id_rsa.pub"
    dest: "/home/ansible/.ssh/authorized_keys"
    owner: ansible
    group: ansible
    mode: "0644"
  when: authorized_keys.stat.exists

- name: save copy of ansible user ssh keys
  copy:
    src: "/home/ansible/.ssh/authorized_keys"
    dest: "{{ local_dir }}/ansible.id_rsa.pub"
    remote_src: true
    mode: 0777
  when: local_dir is defined
