#!/bin/bash

if [ ! $1 ] || [ ! $2 ] || [ ! $3 ]
then
    echo 'Usage: $( basename $0 ) LIST_NAME DOMAIN LIST_ADMIN_EMAIL_ADDR [PASSWORD]'
    exit 1
fi

listname=$1
domain=$2
email=$3
user_password=${4:-"password"}

newlist -q $listname $email $user_password

/bin/cat <<ALIASES >> /etc/aliases

$listname:              "|/var/lib/mailman/mail/mailman post $listname"
$listname-admin:        "|/var/lib/mailman/mail/mailman admin $listname"
$listname-bounces:      "|/var/lib/mailman/mail/mailman bounces $listname"
$listname-confirm:      "|/var/lib/mailman/mail/mailman confirm $listname"
$listname-join:         "|/var/lib/mailman/mail/mailman join $listname"
$listname-leave:        "|/var/lib/mailman/mail/mailman leave $listname"
$listname-owner:        "|/var/lib/mailman/mail/mailman owner $listname"
$listname-request:      "|/var/lib/mailman/mail/mailman request $listname"
$listname-subscribe:    "|/var/lib/mailman/mail/mailman subscribe $listname"
$listname-unsubscribe:  "|/var/lib/mailman/mail/mailman unsubscribe $listname"
ALIASES

newaliases

if [ -f /etc/mailman/aliases ]
then
    echo '' >> /etc/mailman/aliases
fi

/bin/cat <<ALIASES >> /etc/mailman/aliases
$listname@$domain             $listname@localhost
$listname-admin@$domain       $listname-admin@localhost
$listname-bounces@$domain     $listname-bounces@localhost
$listname-confirm@$domain     $listname-confirm@localhost
$listname-join@$domain        $listname-join@localhost
$listname-leave@$domain       $listname-leave@localhost
$listname-owner@$domain       $listname-owner@localhost
$listname-request@$domain     $listname-request@localhost
$listname-subscribe@$domain   $listname-subscribe@localhost
$listname-unsubscribe@$domain $listname-unsubscribe@localhost
ALIASES

postmap /etc/mailman/aliases
postfix reload
service mailman restart
