---
- name: nginx conf alteration
  blockinfile:
    path: "/etc/nginx/sites-available/{{ domain }}"
    insertbefore: '\} # 80'
    block: |
        location = / {
            alias /var/www/{{ domain }}/wordpress/index.php;
            include params/fastcgi_params;
            fastcgi_intercept_errors on;
            fastcgi_pass php;
        }
        location /wordpress {
            root /var/www/{{ domain }};
            include snippets/fastcgi_php.conf;
            try_files $uri $uri/ /wordpress/index.php?$args;
        }
        location ~ ^/(feed|page|page-.+) {
            alias /var/www/{{ domain }}/wordpress/index.php;
            include params/fastcgi_params;
            fastcgi_intercept_errors on;
            fastcgi_pass php;
        }
        location ~ ^/wp-.+ {
            root /var/www/{{ domain }}/wordpress;
            include snippets/fastcgi_php.conf;
        }
        location /wp-content/database {
            deny all;
        }
  register: nginx_conf

- import_tasks: install.yml
  when: nginx_conf is changed

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx_conf is changed

- import_tasks: ../../../end.yml
