---
- name: nginx conf alteration
  blockinfile:
    path: "/etc/nginx/sites-available/{{ domain }}"
    block: "{{ lookup( 'template', 'nginx_80_block.j2' ) }}"
    marker: '    # {mark} ANSIBLE MANAGED WORDPRESS BLOCK'
    insertbefore: '\} # 80'
  register: nginx_conf

- import_tasks: install.yml
  when: nginx_conf is changed

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx_conf is changed

- import_tasks: ../../../end.yml
