---
- stat:
    path: /etc/nginx/params
  register: st

- import_tasks: params.yml
  when: st.stat.exists == false
  notify: restart nginx

- name: install nginx.conf file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: install proxy.conf file
  copy:
    src: proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf
  notify: restart nginx

- name: install server.conf file
  copy:
    src: server.conf
    dest: /etc/nginx/snippets/server.conf
  notify: restart nginx

- name: install ssl_params.conf file
  copy:
    src: ssl_params.conf
    dest: /etc/nginx/snippets/ssl_params.conf
  notify: restart nginx

- name: build ssl_conf file
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/snippets/ssl.conf
  notify: restart nginx

- name: install fastcgi_params file
  copy:
    src: fastcgi_params
    dest: /etc/nginx/params/fastcgi_params
  notify: restart nginx

- name: delete unused (and probably later overwritten) snippets
  file:
    path: "/etc/nginx/{{ item }}/snippets"
    state: absent
  with_items:
    - fastcgi.conf
    - fastcgi-php.conf
    - snakeoil.conf
