---
- name: install nginx
  apt:
    update_cache: yes
    cache_valid_time: 86400
    pkg: nginx
    state: latest
  notify: restart nginx

- import_tasks: conf.yml
- import_tasks: certificate.yml
- import_tasks: error_pages.yml
- import_tasks: web_site.yml
- import_tasks: shorewall.yml
- import_tasks: fail2ban.yml
