---
- stat:
    path: "{{ perlbrew_root }}/bin"
  register: pb

- name: download perlbrew
  get_url:
    url: http://install.perlbrew.pl
    dest: /tmp/install.perlbrew.pl
    mode: 0700
  when: pb.stat.exists == false

- name: install perlbrew
  shell: cat /tmp/install.perlbrew.pl | /bin/bash
  environment:
    PERLBREW_ROOT: "{{ perlbrew_root }}"
  when: pb.stat.exists == false
  register: perlbrew_installed

- name: remove perlbrew source
  file:
    path: /tmp/install.perlbrew.pl
    state: absent

- name: bash.bashrc sources perlbrew bashrc
  lineinfile:
    dest: /etc/bash.bashrc
    line: ". {{ perlbrew_root }}/etc/bashrc"

- name: perlbrew-cron
  template:
    src: perlbrew-cron.j2
    dest: /usr/local/bin/perlbrew-cron
    owner: root
    group: root
    mode: '0755'

- name: upgrade perlbrew, install cpanm, install stable
  shell: |
    . {{ perlbrew_root }}/etc/bashrc
    perlbrew self-upgrade >/dev/null 2>&1
    perlbrew -f install-cpanm >/dev/null 2>&1
    perlbrew install --notest --switch {{ perl_version }} >/dev/null 2>&1
    exit 0
  args:
    executable: /bin/bash
  changed_when: false
  when: perlbrew_installed|changed

- name: copy local_lib.bash
  template:
    src: local_lib.bash.j2
    dest: /tmp/local_lib.bash
    mode: '0755'
  when: dev_user is defined and dev_user != '' and perlbrew_installed|changed

- name: copy cpanfile
  copy:
    src: cpanfile
    dest: /tmp/cpanfile
  when: dev_user is defined and dev_user != '' and perlbrew_installed|changed

- name: create local lib, switch to it, and install libs from cpanfile
  command: /tmp/local_lib.bash
  changed_when: false
  when: dev_user is defined and dev_user != '' and perlbrew_installed|changed

- name: remove local_lib.bash
  file:
    path: /tmp/local_lib.bash
    state: absent

- name: remove cpanfile
  file:
    path: /tmp/cpanfile
    state: absent
