---
- stat:
    path: "/home/{{ user }}/backups"
  register: st

- name: backup directory
  file:
    path: "/home/{{ user }}/backups"
    state: directory
    mode: '0775'
  when: st.stat.exists == false

- stat:
    path: "/home/{{ user }}/backups/rsync.sh"
  register: st

- name: link rsync script
  file:
    src: "/host/etc/backups/rsync.sh"
    dest: "/home/{{ user }}/backups/rsync.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  when: st.stat.exists == false

- stat:
    path: "/home/{{ user }}/backups/archive.sh"
  register: st

- name: link archive script
  file:
    src: "/host/etc/backups/archive.sh"
    dest: "/home/{{ user }}/backups/archive.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  when: st.stat.exists == false

- import_tasks: ../../../end.yml
