---
# See: https://docs.docker.com/engine/install/debian/

- name: install docker prereq packages
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
      - software-properties-common
      - lsb-release
    state: latest

- name: check if apt-key installed
  command: apt-key fingerprint 0EBFCD88
  register: aptkey_fingerprint
  changed_when: false

- name: download apt key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /tmp/docker_aptkey_fingerprint
    mode: 0600
  when: aptkey_fingerprint.stdout == ""
  register: download_apt_key

- name: install apt key
  command: apt-key add /tmp/docker_aptkey_fingerprint
  when: download_apt_key is changed

- name: remove apt key download file
  file:
    path: /tmp/docker_aptkey_fingerprint
    state: absent

- name: add apt repository
  shell: >
    add-apt-repository
    "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian
    $(lsb_release -cs) stable"
  when: aptkey_fingerprint.stdout == ""

- name: update cache
  apt:
    update_cache: yes
  when: aptkey_fingerprint.stdout == ""

- name: install docker
  apt:
    update_cache: yes
    cache_valid_time: 86400
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    force: yes
  register: docker_engine_installed

- name: install docker-py
  pip:
    name: docker-py
  when: docker_engine_installed is changed
