VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 2.0.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box                        = "bento/debian-9.3"
    config.vm.box_version                = "201802.02.0"
    config.vm.box_download_checksum      = "c886437574fa5b32f442d80ec5374066c9ef12cea92056f983faf5e71c72731e"
    config.vm.box_download_checksum_type = "sha256"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.customize ["modifyvm", :id, "--vram", "20"]
        vb.customize ["modifyvm", :id, "--vrde", "off"]
    end
    
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.provision "shell", inline: "apt-get -q -y update && apt-get -q -y upgrade"
    config.vm.provision "shell",
        name: "Ansible User",
        path: "../../providers/ansible_user.bash",
        env: { "LOCAL_DIR" => "/host/local" }

    config.vm.define taunton do |node|
        node.vm.hostname = taunton
        node.vm.provider "virtualbox" do |vb|
            vb.name   = "Taunton Dev VM"
            vb.memory = 1024
            vb.cpus   = 1
        end

        node.vm.network "private_network", ip: "10.42.0.42"
        node.vm.network "public_network"
        node.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
        node.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 22, host: 2242
                
        node.vm.synced_folder "../../../", synced_folder, SharedFoldersEnableSymlinksCreate: false

        node.vm.provision "shell",
            name: "Ansible",
            path: "../../providers/ansible.bash",
            env: { "HOSTS" => "/host/vagrant/configs/taunton/hosts" }

        node.vm.provision "shell",
            name: "Ansible Playbook",
            inline:
                "su -l ansible -c 'cd /host/ansible; " +
                "PYTHONUNBUFFERED=1 LOCAL_DIR=/host/local SRC_DIR=/host " +
                "ansible-playbook -i inventories/taunton.ini playbooks/all.yml" + "'"
    end
end
