---
- stat:
    path: /etc/fail2ban/jail.d
  register: st

- name: install fail2ban rules
  copy:
    src: fail2ban.rules
    dest: /etc/fail2ban/jail.d/postfix.conf
  when: st.stat.exists == true
  notify: restart fail2ban
