---
- stat:
    path: /etc/shorewall/rules.d
  register: sw_st

- name: install shorewall rules
  copy:
    src: shorewall.rules
    dest: /etc/shorewall/rules.d/postfix
  when: sw_st.stat.exists == true
  notify: restart shorewall

- stat:
    path: /etc/fail2ban/jail.d
  register: f2b_st

- name: install fail2ban rules
  copy:
    src: fail2ban.rules
    dest: /etc/fail2ban/jail.d/postfix.conf
  when: f2b_st.stat.exists == true
  notify: restart fail2ban

- name: updated courier-auth filter
  replace:
    dest: /etc/fail2ban/filter.d/courier-auth.conf
    regexp: 'user'
    replace: '(?:user|method)'
  notify: restart fail2ban

- name: touch /etc/shorewall/rules.d/blacklists/fail2ban_repeaters
  file:
    path: /etc/shorewall/rules.d/blacklists/fail2ban_repeaters
    state: touch
    modification_time: preserve
    access_time: preserve
  when: sw_st.stat.exists == true and f2b_st.stat.exists == true

- name: install daily cron shorewall_fail2ban
  copy:
    src: shorewall_fail2ban.cron
    dest: /etc/cron.daily/shorewall_fail2ban
    mode: '0755'
  when: sw_st.stat.exists == true and f2b_st.stat.exists == true
