---
- user:
    name: ansible
    shell: /bin/bash
    groups: "sudo"
    append: yes
  register: ansible_user_settings

- name: add ansible to sudo
  copy:
    src: 98_ansible
    dest: /etc/sudoers.d/98_ansible

- import_tasks: id_rsa.yml
- import_tasks: password.yml
