---
- local_action:
    module: stat
    path: "{{ local_dir }}/ansible.id_rsa"
  register: id_rsa
  when: local_dir is defined

- name: copy in ansible user id_rsa
  copy:
    src: "{{ local_dir }}/ansible.id_rsa"
    dest: "/home/ansible/.ssh/id_rsa"
    owner: ansible
    group: ansible
    mode: "0600"
  when: id_rsa.stat.exists

- name: save copy of ansible user ssh keys
  copy:
    src: "/home/ansible/.ssh/id_rsa"
    dest: "{{ local_dir }}/ansible.id_rsa"
    remote_src: true
  when: local_dir is defined

- import_tasks: ../../../end.yml
