---
- stat:
    path: "{{ perlbrew_root }}/bin"
  register: pb

- name: download perlbrew
  get_url:
    url: http://install.perlbrew.pl
    dest: /tmp/install.perlbrew.pl
    mode: 0700
  when: pb.stat.exists == false

- name: install perlbrew
  shell: cat /tmp/install.perlbrew.pl | /bin/bash
  environment:
    PERLBREW_ROOT: "{{ perlbrew_root }}"
  when: pb.stat.exists == false
  register: perlbrew_installed

- name: remove perlbrew source
  file:
    path: /tmp/install.perlbrew.pl
    state: absent

- name: bash.bashrc sources perlbrew bashrc
  lineinfile:
    dest: /etc/bash.bashrc
    line: "builtin source {{ perlbrew_root }}/etc/bashrc"

- name: perlbrew-cron
  template:
    src: perlbrew-cron.j2
    dest: /usr/local/bin/perlbrew-cron
    owner: root
    group: root
    mode: '0755'

- name: upgrade perlbrew, install cpanm, install stable
  shell: |
    builtin source {{ perlbrew_root }}/etc/bashrc
    perlbrew self-upgrade >/dev/null 2>&1
    perlbrew -f install-cpanm >/dev/null 2>&1
    perlbrew install --notest {{ perl_version }} >/dev/null 2>&1
    exit 0
  args:
    executable: /bin/bash
  changed_when: false
  when: perlbrew_installed is changed

- name: remove perlbrew help text file
  file:
    path: /tmp/perlbrew
    state: absent

- name: perlbrew lib create and switch for dev user
  shell: |
    builtin source {{ perlbrew_root }}/etc/bashrc
    perlbrew lib create $(perlbrew list | head -1 | sed -e 's/[ ]*//g')@local
    perlbrew switch $(perlbrew list | tail -1 | sed -e 's/[ ]*//g')
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ user }}"
  when: user_executed is defined and perlbrew_installed is changed

- import_tasks: ../../../end.yml
