---
- name: /etc/hosts domain exists
  replace:
    dest: /etc/hosts
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - { regexp: '127\.0\.0\.1\s+localhost$', replace: '127.0.0.1 localhost.localdomain localhost' }
    - {
        regexp: '127\.0\.0\.1\s+{{ ansible_hostname }}\s+{{ ansible_hostname }}$',
        replace: '127.0.0.1 {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}',
    }

- name: set mailname
  copy:
    content: "{{ mailhost }}"
    dest: /etc/mailname
