---
- name: ensure credentials.ini exists
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: answer
    value: 42
  when: local_dir is defined

- name: load root password from credentials.ini
  set_fact:
    root_password: "{{ lookup( 'ini', 'root_password file={{ local_dir }}/credentials.ini' ) }}"
  when: local_dir is defined and ( root_password == '' or root_password == [] )

- name: set if root password not defined
  set_fact:
    credential_not_defined: 1
  when: root_password == '' or root_password == []

- name: generate password
  command: /usr/bin/openssl rand -base64 15
  register: generated_password
  when: credential_not_defined is defined

- name: set password variable
  set_fact:
    root_password: "{{ generated_password.stdout }}"
  when: credential_not_defined is defined

- name: write generated password to credentials.ini
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: root_password
    value: "{{ root_password }}"
  when: local_dir is defined and credential_not_defined is defined

- name: set root password
  user:
    name: root
    update_password: always
    password: "{{ root_password }}"
