---
- name: install fail2ban
  apt:
    update_cache: yes
    cache_valid_time: 86400
    pkg: fail2ban
    state: latest

- name: copy jail.local
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0644
  notify: restart fail2ban

- name: copy ssh.conf
  copy:
    src: ssh.conf
    dest: /etc/fail2ban/jail.d/ssh.conf
    mode: 0644
  notify: restart fail2ban

- name: copy nginx-req-limit.conf
  copy:
    src: nginx-req-limit.conf
    dest: /etc/fail2ban/filter.d/nginx-req-limit.conf
    mode: 0644
  notify: restart fail2ban

- name: copy action.local
  copy:
    src: action.local
    dest: /etc/fail2ban/action.d/{{ item }}
    mode: 0644
  with_items:
    - mail
    - mail-buffered
    - mail-whois
    - mail-whois-lines
    - sendmail
    - sendmail-buffered
    - sendmail-whois
    - sendmail-whois-lines
  notify: restart fail2ban

- name: delete defaults-debian.conf
  file:
    state: absent
    path: /etc/fail2ban/jail.d/defaults-debian.conf
  notify: restart fail2ban

- stat:
    path: /etc/shorewall/rules.d
  register: sw_st

- name: copy blacklist
  copy:
    src: blacklist
    dest: /etc/cron.hourly/blacklist
    owner: root
    group: root
    mode: '0700'
  when: sw_st.stat.exists == true

- name: copy unblacklist
  copy:
    src: unblacklist
    dest: /etc/cron.monthly/unblacklist
    owner: root
    group: root
    mode: '0700'
  when: sw_st.stat.exists == true

- import_tasks: ../../../end.yml
