---
- name: install exim4
  apt:
    update_cache: yes
    cache_valid_time: 86400
    pkg: exim4
    state: latest

- name: backup /etc/exim4/update-exim4.conf.conf dist file
  copy:
    src: /etc/exim4/update-exim4.conf.conf
    dest: /etc/exim4/update-exim4.conf.conf.dist
    force: no

- name: build /etc/exim4/update-exim4.conf.conf file
  template:
    src: update-exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: 0644
  register: exim_conf_change

- name: update exim4 conf
  command: update-exim4.conf
  when: exim_conf_change is changed

- name: restart exim4
  service:
    name: exim4
    state: restarted
  when: exim_conf_change is changed
