---
- name: install python-passlib
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg: python-passlib
    state: latest

- name: install FastCGI Perl
  include_role:
    name: fastcgi_perl
    allow_duplicates: no
    public: yes

- name: install FastCGI PHP
  include_role:
    name: fastcgi_php
    allow_duplicates: no
    public: yes

- name: ensure credentials.ini exists
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: answer
    value: "42"
  when: local_dir is defined

- name: load user name
  set_fact:
    user: "{{ lookup( 'ini', 'user file={{ local_dir }}/credentials.ini default=user' ) }}"
  when:
    - local_dir is defined
    - user == '' or user == []

- name: load user password
  set_fact:
    user_password: "{{ lookup( 'ini', 'user_password file={{ local_dir }}/credentials.ini' ) }}"
  when:
    - local_dir is defined
    - user_password == '' or user_password == []

- name: create nagios htpasswd.users file
  htpasswd:
    path: /etc/nagios/htpasswd.users
    name: "{{ user }}"
    password: "{{ user_password }}"
    owner: root
    group: root
    mode: 0644
    crypt_scheme: des_crypt
  when:
    - user is defined
    - user_password is defined

- name: install nginx conf files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/snippets/{{ item }}"
  with_items:
    - nagios_ui_80.conf
    - nagios_ui_443.conf
  register: web_conf_snippets

- name: inject nagios_ui into default web site
  lineinfile:
    path: "/etc/nginx/sites-available/{{ domain }}"
    line: "    include snippets/nagios_ui_{{ item }}.conf;"
    regexp: "    include snippets/nagios_ui_{{ item }}.conf;"
    insertbefore: "^\\} # {{ item }}$"
  with_items:
    - 80
    - 443
  register: web_conf

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: web_conf_snippets is changed or web_conf.results.0.msg == "line added" or web_conf.results.1.msg == "line added"

- name: set nagios admin auth
  replace:
    dest: /etc/nagios/cgi.cfg
    regexp: '(authorized_for_[^=]+=nagiosadmin)$'
    replace: '\1,{{ user }}'
  register: nagios_conf

- name: restart nagios
  service:
    name: nagios
    state: restarted
  when: nagios_conf is changed
