#!/usr/bin/env perl

my $REGEXP = shift || die "no email-adress given (regexp-style, e.g. bl.*\@yahoo.com)!";
my @data   = qx</usr/sbin/postqueue -p>;

for (@data) {
    if ( /^(\w+)(\*|\!)?\s/ ) {
        $queue_id = $1;
    }

    if ( $queue_id ) {
        if ( /$REGEXP/i ) {
            $Q{$queue_id} = 1;
            $queue_id     = '';
        }
    }
}

open( my $postsuper, '|postsuper -d -' ) or die q{Couldn't open postsuper};
print $postsuper "$_\n" for keys %Q;
