---
- name: install mailman
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg: '{{ mailman_packages }}'
    state: latest

- name: copy 41_valias_maps_mailman.cf
  copy:
    src: 41_valias_maps_mailman.cf
    dest: /etc/postfix/main.cf.d/41_valias_maps.cf
  notify: assemble main_cf

- name: setup utility scripts
  copy:
    src: '{{ item }}'
    dest: '/root/{{ item }}'
    mode: '0744'
  with_items:
    - create-mailman-list
    - export-mm-data
