---
- name: conf dir check for root
  stat:
    path: /root/.conf
  register: conf_dir

- name: git clone conf via https for root
  git:
    repo: https://github.com/gryphonshafer/.conf.git
    version: master
    dest: /root/.conf
  when: conf_dir.stat.exists == false

- name: install configuration for root
  command: /root/.conf/install
  register: install_conf
  when: conf_dir.stat.exists == false
  changed_when: install_conf.stdout | regex_search('(Successfully installed:)')
