---
- name: ensure credentials.ini exists
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: answer
    value: "42"
  when: local_dir is defined

- name: load salt
  set_fact:
    salt: "{{ lookup( 'ini', 'salt file={{ local_dir }}/credentials.ini' ) }}"
  when: local_dir is defined

- name: load user name
  set_fact:
    user: "{{ lookup( 'ini', 'user file={{ local_dir }}/credentials.ini default=user' ) }}"
  when:
    - local_dir is defined
    - user == '' or user == []

- name: load user email
  set_fact:
    user_email: "{{ lookup( 'ini', 'user_email file={{ local_dir }}/credentials.ini default=user' ) }}"
  when:
    - local_dir is defined
    - user_email == '' or user_email == []

- name: write user name
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: user
    value: "{{ user }}"
  when: local_dir is defined

- name: write user email
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: user_email
    value: "{{ user_email }}"
  when: local_dir is defined

- name: set if salt not defined
  set_fact:
    salt_not_defined: 1
  when: salt == '' or salt == []

- name: generate salt
  command: /usr/bin/openssl rand -base64 12
  register: generated_salt
  when: salt_not_defined is defined

- name: set salt variable
  set_fact:
    salt: "{{ generated_salt.stdout }}"
  when: salt_not_defined is defined

- name: write generated salt to credentials.ini
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: salt
    value: "{{ salt }}"
  when: local_dir is defined and salt_not_defined is defined

- name: load user password
  set_fact:
    user_password: "{{ lookup( 'ini', 'user_password file={{ local_dir }}/credentials.ini' ) }}"
  when: local_dir is defined and ( user_password == '' or user_password == [] )

- name: set if password not defined
  set_fact:
    credential_not_defined: 1
  when: user_password == '' or user_password == []

- name: generate a password
  command: /usr/bin/openssl rand -base64 12
  register: generated_password
  when: credential_not_defined is defined

- name: set password variable
  set_fact:
    user_password: "{{ generated_password.stdout }}"
  when: credential_not_defined is defined

- name: write generated password to credentials.ini
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: user_password
    value: "{{ user_password }}"
  when: local_dir is defined and credential_not_defined is defined
