---
- name: create user
  user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: sudo
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
  register: create_user

- name: set user password
  user:
    name: "{{ user }}"
    update_password: always
    password: "{{ user_password | password_hash( 'sha512', salt ) }}"

- name: move authorized_keys file
  command: mv /home/{{ user }}/.ssh/id_rsa.pub /home/{{ user }}/.ssh/authorized_keys
  when: create_user.ssh_public_key != none

- name: add user to nopasswd sudoers
  copy:
    content: "{{ user }} ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/42_{{ user }}
    mode: 0440

- name: setup email alias for dev user
  replace:
    dest: /etc/aliases
    regexp: '^root: \S+'
    replace: 'root: {{ user_email }}'
  register: new_prime_alias

- name: newaliases
  command: newaliases
  when: new_prime_alias is changed
