---
- stat:
    path: /etc/apt/sources.list.d/php.list
  register: php_source

- name: get php gpg and set php in sources list
  shell: |
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list
  when: php_source.stat.exists == false

- name: install FastCGI PHP packages
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg:
      - php8.2
      - php8.2-cgi
      - php8.2-sqlite3
      - php8.2-curl
      - php8.2-xml
      - php-common
    state: latest

- name: find php version directory
  find:
    paths: /etc/php
    file_type: directory
  register: php_version

- name: fix_pathinfo set to 0 in php.ini
  lineinfile:
    path: "{{ php_version.files[-1].path }}/cgi/php.ini"
    line: 'cgi.fix_pathinfo = 0;'

- name: install php-fcgi default
  copy:
    src: default_php-fcgi
    dest: /etc/default/php-fcgi
    owner: root
    group: root
    mode: 0644

- name: install php-fcgi init.d
  copy:
    src: init.d_php-fcgi
    dest: /etc/init.d/php-fcgi
    owner: root
    group: root
    mode: 0755
  register: fcgi_init

- name: update rc php-fcgi defaults
  command: update-rc.d php-fcgi defaults
  when: fcgi_init is changed

- name: restart php-fcgi
  service:
    name: php-fcgi
    state: restarted
  when: fcgi_init is changed

- name: create nginx upstreams.conf
  copy:
    content: ""
    dest: /etc/nginx/conf.d/upstreams.conf
    force: no

- name: append to nginx upstreams.conf
  blockinfile:
    path: /etc/nginx/conf.d/upstreams.conf
    marker: '# {mark} ANSIBLE MANAGED PHP BLOCK'
    block: |
        upstream php {
            server 127.0.0.1:9000;
        }

- name: install nginx fastcgi_php.conf
  copy:
    src: fastcgi_php.conf
    dest: /etc/nginx/snippets/fastcgi_php.conf
    mode: 0644

- name: index index.php
  lineinfile:
    path: "/etc/nginx/sites-available/{{ domain }}"
    regexp: '\bindex\s+index\.php;'
    line: '    index index.php;'
    insertafter: '^\s*index\s+'

- import_tasks: ../../../end.yml
