---
- name: set hostname via file
  copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/hostname
  register: set_hostname

- name: set hostname via command
  command: "hostname {{ inventory_hostname }}"
  when: set_hostname is changed

- name: set mailname
  copy:
    content: "{{ mailhost }}\n"
    dest: /etc/mailname

- name: /etc/hosts domain lines change
  replace:
    dest: /etc/hosts
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  with_items:
    - {
        regexp: '127\.0\.0\.1\s+localhost$',
        replace: '127.0.0.1 localhost.localdomain localhost {{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}'
    }

- name: /etc/hosts domain lines clean
  lineinfile:
    path: /etc/hosts
    regexp: '127\.0\.\d+\.1\s+{{ inventory_hostname }}\s+{{ inventory_hostname }}$'
    state: absent
