---
- name: backup /etc/apt/sources.list dist file
  copy:
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.dist
    force: no

- name: add contrib to /etc/apt/sources.list
  replace:
    dest: /etc/apt/sources.list
    regexp: ' main$'
    replace: ' main contrib'

- name: install system packages
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg: '{{ system_packages }}'
    state: latest

- name: install rsyslog
  apt:
    pkg: rsyslog
    state: latest
  notify: restart rsyslog

- name: install usability packages
  apt:
    pkg: '{{ usability_packages }}'
    state: latest
