---
- name: backup /etc/apt/sources.list dist file
  copy:
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.dist
    force: no
    mode: 0644

- name: add contrib to /etc/apt/sources.list
  replace:
    dest: /etc/apt/sources.list
    regexp: ' main$'
    replace: ' main contrib'

- name: check if python3-apt installed
  shell: "dpkg -l python3-apt | grep '^ii' || true"
  changed_when: no
  register: pacheck

- name: install python3-apt
  command: apt-get -q -y install python3-apt
  args:
    warn: no
  when: pacheck.stdout_lines | length == 0

- name: install aptitude
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg: aptitude
    state: latest
    force_apt_get: yes

- name: install system packages
  apt:
    pkg: '{{ system_packages }}'
    state: latest

- name: install rsyslog
  apt:
    pkg: rsyslog
    state: latest
  notify: restart rsyslog

- name: install usability packages
  apt:
    pkg: '{{ usability_packages }}'
    state: latest
