---
- name: install screen
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg: screen
    state: latest
  register: screen_installed

- name: set screen files
  when: screen_installed is success
  file:
    path: '{{ item.path }}'
    mode: '{{ item.mode }}'
  with_items:
    - { path: '/usr/bin/screen', mode: '2755' }
    - { path: '/var/run/screen', mode: '0775' }
    - { path: '/run/screen',     mode: '0777' }
