---
- name: ensure credentials.ini exists
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: answer
    value: 42
  when: local_dir is defined

- name: load dev user name
  set_fact:
    user: "{{ lookup( 'ini', 'user file={{ local_dir }}/credentials.ini default=dev' ) }}"
  when: local_dir is defined and ( user == '' or user == [] )

- name: write dev user name
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: user
    value: "{{ user }}"
  when: local_dir is defined

- name: load dev user email
  set_fact:
    user_email: "{{ lookup( 'ini', 'user_email file={{ local_dir }}/credentials.ini default=dev' ) }}"
  when: local_dir is defined and ( user_email == '' or user_email == [] )

- name: write dev user email
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: user_email
    value: "{{ user_email }}"
  when: local_dir is defined

- name: load dev user password
  set_fact:
    user_password: "{{ lookup( 'ini', 'user_password file={{ local_dir }}/credentials.ini' ) }}"
  when: local_dir is defined and ( user_password == '' or user_password == [] )

- name: set if password not defined
  set_fact:
    credential_not_defined: 1
  when: user_password == '' or user_password == []

- name: generate a password
  command: /usr/bin/openssl rand -base64 15
  register: generated_password
  when: credential_not_defined is defined

- name: set password variable
  set_fact:
    user_password: "{{ generated_password.stdout }}"
  when: credential_not_defined is defined

- name: write generated password to credentials.ini
  ini_file:
    dest: "{{ local_dir }}/credentials.ini"
    section: global
    option: user_password
    value: "{{ user_password }}"
  when: local_dir is defined and credential_not_defined is defined
