---
- stat:
    path: "/home/{{ user }}/.files.tgz"
  register: tgz_bundle_tgz

- name: load tgz_bundle_url from credentials.ini
  set_fact:
    tgz_bundle_url: "{{ lookup( 'ini', 'tgz_bundle_url file={{ local_dir }}/credentials.ini' ) }}"
  when: tgz_bundle_tgz.stat.exists == false and local_dir is defined and ( tgz_bundle_url == '' or tgz_bundle_url == [] )

- name: copy tgz bundle into dev user home dir
  get_url:
    url: "{{ tgz_bundle_url }}"
    dest: "/home/{{ user }}/.files.tgz"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: tgz_bundle_tgz.stat.exists == false and tgz_bundle_url != '' and tgz_bundle_url != []

- unarchive:
    src: "/home/{{ user }}/.files.tgz"
    dest: "/home/{{ user }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: tgz_bundle_tgz.stat.exists == false and tgz_bundle_url != '' and tgz_bundle_url != []

- copy:
    remote_src: true
    src: "/home/{{ user }}/.files.tgz"
    dest: /root/.files.tgz
    owner: root
    group: root
  when: tgz_bundle_tgz.stat.exists == false and tgz_bundle_url != '' and tgz_bundle_url != []

- unarchive:
    src: /root/.files.tgz
    dest: /root
    owner: root
    group: root
    remote_src: true
  when: tgz_bundle_tgz.stat.exists == false and tgz_bundle_url != '' and tgz_bundle_url != []
