---
- hosts: all
  become: true
  roles:
    - base_system
    - ansible_user
    - exim
    - user
    - timezone

- hosts: firewall
  become: true
  roles:
    - shorewall

- hosts: web
  become: true
  roles:
    - nginx

# - hosts: remote
#   become: true
#   roles:
#     - ssh_hardening
#     - ntp
#     - fail2ban
#     - letsencrypt
#     - nagios

# - hosts: gitlab
#   become: true
#   roles:
#     - docker_gitlab

# - hosts: local
#   become: true
#   roles:
#     - de-vagrant
#     - samba

# - hosts: dev
#   become: true
#   roles:
#     - perlbrew
#     - docker

# - hosts: backup
#   become: true
#   roles:
#     - backup_scripts
#     - host_drive_mount
