---
- hosts: all
  become: true
  roles:
    - base_system
    - ansible_user
    - exim

- hosts: docker
  become: true
  roles:
    - docker

- hosts: prod
  become: true
    - shorewall
    - ssh_hardening
    - fail2ban
    - ntp

- hosts: dev
  become: true
  roles:
    - timezone
    - de-vagrant
    - dev_user
    - samba
    - host_drive_mount

- hosts: perl
  become: true
  roles:
    - perlbrew

- hosts: app
  become: true
  roles:
    - nginx
    - perl
    - mysql

- hosts: backups
  become: true
  roles:
    - backup_scripts
