---
- hosts: all
  become: true
  roles:
    - base_system
    - ansible_user
    - exim
    - user
    - timezone

- hosts: security
  become: true
  roles:
    - shorewall
    - fail2ban
    - ssh_hardening

- hosts: web
  become: true
  roles:
    - nginx

- hosts: remote
  become: true
  roles:
    - ntp
    - letsencrypt
    - nagios

- hosts: gitlab
  become: true
  roles:
    - docker_gitlab

- hosts: web_hosting_services
  become: true
  roles:
    - perlbrew
    - docker
    - sqlite

- hosts: web_hosting
  become: true
  roles:
    - perlbrew_production_user
    - irc

- hosts: local
  become: true
  roles:
    - devagrant
    - samba

- hosts: dev
  become: true
  roles:
    - mysql

- hosts: backup
  become: true
  roles:
    - backup_scripts
    - host_drive_mount

- hosts: ansible
  become: true
  roles:
    - ansible_user_private
