---
- hosts: all
  become: true
  roles:
    - base_system
    - ansible_user
    - exim

- hosts: production
  become: true
  roles:
    - shorewall
    - ssh_hardening
    - fail2ban
    - ntp

- hosts: user
  become: true
  roles:
    - timezone
    - user

- hosts: local
  become: true
  roles:
    - de-vagrant
    - samba
    - perlbrew
    - docker

- hosts: backup
  become: true
  roles:
    - backup_scripts
    - host_drive_mount

- hosts: web
  become: true
    - nginx

- hosts: gitlab
  become: true
  roles:
    - docker_gitlab
