---
- hosts: all
  become: true
  roles:
    - base_system
    - ansible_user
    - exim

- hosts: prod
  become: true
  roles:
    - shorewall
    - ssh_hardening
    - fail2ban
    - ntp

- hosts: user
  become: true
    - timezone
    - user

- hosts: docker
  become: true
  roles:
    - docker

- hosts: local
  become: true
  roles:
    - de-vagrant
    - samba
    - host_drive_mount

- hosts: perl
  become: true
  roles:
    - perlbrew

- hosts: web
  become: true
    - nginx

- hosts: app
  become: true
  roles:
    - perl
    - mysql

- hosts: backup_tools
  become: true
  roles:
    - backup_scripts
