---
- hosts: all
  become: true
  roles:
    - base_system          # system
    - ansible_user         # system
    - ansible_user_private # system
    - timezone             # system
    - ntp                  # system

    - ssh_hardening        # security
    - shorewall            # security
    - fail2ban             # security
    - nagios               # security

    - user                 # dev
    - samba                # services (user)

    - exim                 # services
    - irc                  # services
    - mysql                # services
    - sqlite               # services

    - nginx                # services
    - fastcgi_perl         # services (nginx)
    - fastcgi_php          # services (nginx)
    - letsencrypt          # security (nginx)
    - trac                 # services (nginx)
    - wordpress            # services (fastcgi_php, sqlite)

    - postfix              # services
    - mailman              # services (fastcgi_perl)
    - roundcube            # services (fastcgi_php)

    - docker               # services
    - docker_gitlab        # docker (nginx, docker)
    - docker_mysql         # docker (docker)
    - docker_perl          # docker (docker)

    - backup_scripts       # specific (user)
    - host_drive_mount     # specific (user, samba)
    - ops_user             # specific

    - perlbrew             # dev
    - sass                 # dev
    - de_vagrant           # system

    - node                 # dev
