---
- name: add stretch backports apt repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main

- name: install certbot with nginx plugin
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg: python-certbot-nginx
    state: latest
    default_release: stretch-backports
  register: install_certbot

- name: register certbot
  command: 'certbot register -m "{{ user_email }}" --agree-tos'
  when: install_certbot.changed
  changed_when: false

- name: certbot webroot map call
  command: "certbot certonly -a webroot --webroot-map '{{ webroot_map }}'"
  when: webroot_map | length > 0
  changed_when: false

- name: nginx sites available ssl conf
  replace:
    dest: '/etc/nginx/sites-available/{{ item.conf }}'
    regexp: '^(\s+)include snippets/ssl.conf;\n'
    replace: |
      \n\1include snippets/ssl_params.conf;
      \1ssl_certificate     /etc/letsencrypt/live/{{ item.key }}/fullchain.pem;
      \1ssl_certificate_key /etc/letsencrypt/live/{{ item.key }}/privkey.pem;
  with_items: "{{ sites_available }}"
  when: sites_available != '' and sites_available != []

- import_tasks: ../../../end.yml
