---
- stat:
    path: /etc/shorewall/rules.d
  register: st

- name: install shorewall rules
  copy:
    src: shorewall.rules
    dest: /etc/shorewall/rules.d/irc
  when: st.stat.exists == true

- name: restart shorewall
  service:
    name: shorewall
    state: restarted
  when: st.stat.exists == true
