---
- name: create cifs credentials file
  template:
    src: credentials.j2
    dest: "/home/{{ dev_user }}/.hdmount"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: 0600

- name: setup mounting functions
  template:
    src: functions.j2
    dest: "/home/{{ dev_user }}/.hdmountrc"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: 0644

- name: load .backuprc in .localrc
  lineinfile:
    dest: "/home/{{ dev_user }}/.localrc"
    create: yes
    state: present
    line: ". ~/.hdmountrc"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
