---
- file:
    src: "/host/etc/{{ item }}"
    dest: "/home/{{ dev_user }}/{{ item }}"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    state: link
  with_items:
    - pull_backups.sh
    - make_archives.sh
