---
- name: install ntp and ntpdate
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg:
      - ntp
      - ntpdate
    state: latest

- import_tasks: ../../../end.yml
