---
- name: setup mounting functions
  template:
    src: functions.j2
    dest: "/home/{{ user }}/.hdmountrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: load .backuprc in .localrc
  lineinfile:
    dest: "/home/{{ user }}/.localrc"
    create: yes
    state: present
    line: ". ~/.hdmountrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- import_tasks: ../../../end.yml
