---
- name: create dev user
  user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    groups: sudo
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
  register: create_dev_user

- name: set root password
  user:
    name: "{{ dev_user }}"
    update_password: always
    password: "{{ dev_user_password }}"

- name: move authorized_keys file
  command: mv /home/{{ dev_user }}/.ssh/id_rsa.pub /home/{{ dev_user }}/.ssh/authorized_keys
  when: create_dev_user.ssh_public_key != none

- name: add user to nopasswd sudoers
  copy:
    content: "{{ dev_user }} ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/42_{{ dev_user }}

- name: setup email alias for dev user
  replace:
    dest: /etc/aliases
    regexp: '^root: \S+'
    replace: 'root: {{ dev_user_email }}'
  register: new_prime_alias

- name: newaliases
  command: newaliases
  when: new_prime_alias|changed
