---
- stat:
    path: "{{ local_dir }}/{{ dev_user }}.id_rsa"
  register: id_rsa
  when: local_dir is defined

- name: copy in dev user id_rsa
  copy:
    src: "{{ local_dir }}/{{ dev_user }}.id_rsa"
    dest: "/home/{{ dev_user }}/.ssh/id_rsa"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0600"
  when: id_rsa.stat.exists

- stat:
    path: "{{ local_dir }}/{{ dev_user }}.authorized_keys"
  register: authorized_keys
  when: local_dir is defined

- name: copy in dev user authorized_keys
  copy:
    src: "{{ local_dir }}/{{ dev_user }}.authorized_keys"
    dest: "/home/{{ dev_user }}/.ssh/authorized_keys"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: "0644"
  when: authorized_keys.stat.exists

- name: save copy of dev user ssh keys
  copy:
    src: "/home/{{ dev_user }}/.ssh/{{ item }}"
    dest: "{{ local_dir }}/{{ dev_user }}.{{ item }}"
    remote_src: true
  with_items:
    - id_rsa
    - authorized_keys
  when: local_dir is defined
