#!/bin/bash

if [ ! $1 ] || [ ! $2 ]
then
    echo "Usage: $( basename $0 ) USERNAME DOMAIN_NAME"
    exit 1
fi

sed -i "/^$1@$2/d" /etc/courier/userdb /var/vmail/users
makeuserdb
postmap /var/vmail/users
rm -rf /var/vmail/$2/$1
rmdir --ignore-fail-on-non-empty /var/vmail/$2
