---
- name: install FastCGI Perl packages
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    pkg:
      - fcgiwrap
      - spawn-fcgi
    state: latest

- name: install fcgiwrap.env.sh
  copy:
    src: fcgiwrap.env.sh
    dest: /usr/local/bin/fcgiwrap.env.sh
    owner: root
    group: root
    mode: 0755

- name: install fcgiwrap.service
  copy:
    src: fcgiwrap.service
    dest: /lib/systemd/system/fcgiwrap.service
    owner: root
    group: root
    mode: 0644

- name: install fcgiwrap init.d
  copy:
    src: init.d_fcgiwrap
    dest: /etc/init.d/fcgiwrap
    owner: root
    group: root
    mode: 0755
  register: fcgiwrap_init

- name: update rc fcgiwrap defaults and systemctl daemon reload
  command: 'update-rc.d fcgiwrap defaults && systemctl daemon-reload'
  when: fcgiwrap_init is changed

- name: restart fcgiwrap
  service:
    name: fcgiwrap
    state: restarted
  when: fcgiwrap_init is changed

- name: create nginx upstreams.conf
  copy:
    content: ""
    dest: /etc/nginx/conf.d/upstreams.conf
    force: no

- name: append to nginx upstreams.conf
  blockinfile:
    path: /etc/nginx/conf.d/upstreams.conf
    marker: '# {mark} ANSIBLE MANAGED PERL BLOCK'
    block: |
      upstream perl {
          server unix:/var/run/fcgiwrap.socket;
      }

- name: install nginx fastcgi_perl_params
  copy:
    src: fastcgi_perl_params
    dest: /etc/nginx/params/fastcgi_perl_params

- name: install nginx fastcgi_perl.conf
  copy:
    src: fastcgi_perl.conf
    dest: /etc/nginx/snippets/fastcgi_perl.conf

- name: index index.cgi
  lineinfile:
    path: "/etc/nginx/sites-available/{{ domain }}"
    regexp: '\bindex\s+index\.cgi;'
    line: '    index index.cgi;'
    insertafter: '^\s*index\s+'

- import_tasks: ../../../end.yml
